from loguru import logger

not_found: str = 'не выявлено'
not_tested: str = 'не проверялось'
be_away: str = 'отсутствовал'


async def set_values(worksheet):
    """
    :param worksheet:
    :return:
    """
    values = [
        {"coordinate": "C2", "value": "МОСИНЖПРОЕКТ", "row": "2", "column": "3"},
        {"coordinate": "D2", "value": "Отчет о ночной смены", "row": "2", "column": "4"},
        {"coordinate": "C3", "value": "ЛО-МИП-УОТиПБ-2021-007", "row": "3", "column": "3"},
        {"coordinate": "D3", "value": "Значение", "row": "3", "column": "4"},
        {"coordinate": "F3", "value": "Примечание", "row": "3", "column": "6"},
        {"coordinate": "C4", "value": "Общая информация", "row": "4", "column": "3"},
        {"coordinate": "C5", "value": "Обход", "row": "5", "column": "3"},
        {"coordinate": "D5", "value": "Первичный", "row": "5", "column": "4"},
        {"coordinate": "C6", "value": "Дата", "row": "6", "column": "3"},
        {"coordinate": "C7", "value": "Подрядчик", "row": "7", "column": "3"},
        {"coordinate": "D7", "value": "ООО ИНГЕОКОМ", "row": "7", "column": "4"},
        {"coordinate": "C8", "value": "Субподрядчик", "row": "8", "column": "3"},
        {"coordinate": "C9", "value": "Проект", "row": "9", "column": "3"},
        {"coordinate": "D9", "value": "Ст. Терехово", "row": "9", "column": "4"},
        {"coordinate": "C10", "value": "Комиссия", "row": "10", "column": "3"},
        {"coordinate": "D10", "value": "Функция", "row": "10", "column": "4"},
        {"coordinate": "F10", "value": "ФИО", "row": "10", "column": "6"},
        {"coordinate": "D11", "value": "□", "row": "11", "column": "4"},
        {"coordinate": "E11", "value": "Инспектирующие", "row": "11", "column": "5"},
        {"coordinate": "D12", "value": "V", "row": "12", "column": "4"},
        {"coordinate": "E12", "value": "Руководитель строительства", "row": "12", "column": "5"},
        {"coordinate": "F12", "value": f"{be_away}", "row": "12", "column": "6"},
        {"coordinate": "D13", "value": "V", "row": "13", "column": "4"},
        {"coordinate": "E13", "value": "Специалист отдела ПБ", "row": "13", "column": "5"},
        {"coordinate": "D14", "value": "V", "row": "14", "column": "4"},
        {"coordinate": "E14", "value": "Инженер СК", "row": "14", "column": "5"},
        {"coordinate": "F14", "value": f"{be_away}", "row": "14", "column": "6"},
        {"coordinate": "D15", "value": "V", "row": "15", "column": "4"},
        {"coordinate": "E15", "value": "Подрядчик", "row": "15", "column": "5"},
        {"coordinate": "F15", "value": f"{be_away}", "row": "15", "column": "6"},
        {"coordinate": "D16", "value": "V", "row": "16", "column": "4"},
        {"coordinate": "E16", "value": "Субподрядчик", "row": "16", "column": "5"},
        {"coordinate": "C17", "value": "Охрана труда, промышленная безопасность и охрана окружающей среды", "row": "17",
         "column": "3"},
        {"coordinate": "C18", "value": "Наблюдения", "row": "18", "column": "3"},
        {"coordinate": "D18", "value": "Категория несоответствия", "row": "18", "column": "4"},
        {"coordinate": "F18", "value": "№", "row": "18", "column": "6"},
        {"coordinate": "G18", "value": "Несоответствие", "row": "18", "column": "7"},
        {"coordinate": "H18", "value": "Срок", "row": "18", "column": "8"},
        {"coordinate": "D19", "value": "□", "row": "19", "column": "4"},
        {"coordinate": "E19", "value": "Документы ОТ и ПБ", "row": "19", "column": "5"},
        {"coordinate": "G19", "value": f"{not_tested}", "row": "19", "column": "7"},
        {"coordinate": "D20", "value": "□", "row": "20", "column": "4"},
        {"coordinate": "E20", "value": "Обучение/аттестация/квалификация", "row": "20", "column": "5"},
        {"coordinate": "G20", "value": f"{not_tested}", "row": "20", "column": "7"},
        {"coordinate": "D21", "value": "V", "row": "21", "column": "4"},
        {"coordinate": "E21", "value": "СИЗ", "row": "21", "column": "5"},
        {"coordinate": "D22", "value": "V", "row": "22", "column": "4"},
        {"coordinate": "E22", "value": "Механизмы и оборудование", "row": "22", "column": "5"},
        {"coordinate": "G22", "value": f"{not_found}", "row": "22", "column": "7"},
        {"coordinate": "D23", "value": "V", "row": "23", "column": "4"},
        {"coordinate": "E23", "value": "ТС/Спецтехника", "row": "23", "column": "5"},
        {"coordinate": "G23", "value": f"{not_found}", "row": "23", "column": "7"},
        {"coordinate": "D24", "value": "V", "row": "24", "column": "4"},
        {"coordinate": "E24", "value": "Знаки безопасности/ограждения", "row": "24", "column": "5"},
        {"coordinate": "G24", "value": f"{not_found}", "row": "24", "column": "7"},
        {"coordinate": "D25", "value": "V", "row": "25", "column": "4"},
        {"coordinate": "E25", "value": "Земляные работы", "row": "25", "column": "5"},
        {"coordinate": "G25", "value": f"{not_found}", "row": "25", "column": "7"},
        {"coordinate": "D26", "value": "V", "row": "26", "column": "4"},
        {"coordinate": "E26", "value": "Электробезопасность", "row": "26", "column": "5"},
        {"coordinate": "D27", "value": "V", "row": "27", "column": "4"},
        {"coordinate": "E27", "value": "Бетонные работы", "row": "27", "column": "5"},
        {"coordinate": "G27", "value": f"{not_found}", "row": "27", "column": "7"},
        {"coordinate": "D28", "value": "V", "row": "28", "column": "4"},
        {"coordinate": "E28", "value": "ГПМ", "row": "28", "column": "5"},
        {"coordinate": "G28", "value": f"{not_found}", "row": "28", "column": "7"},
        {"coordinate": "D29", "value": "□", "row": "29", "column": "4"},
        {"coordinate": "E29", "value": "Замкнутые пространства", "row": "29", "column": "5"},
        {"coordinate": "G29", "value": f"{not_tested}", "row": "29", "column": "7"},
        {"coordinate": "D30", "value": "V", "row": "30", "column": "4"},
        {"coordinate": "E30", "value": "Ручные инструменты", "row": "30", "column": "5"},
        {"coordinate": "G30", "value": f"{not_found}", "row": "30", "column": "7"},
        {"coordinate": "D31", "value": "V", "row": "31", "column": "4"},
        {"coordinate": "E31", "value": "Работы на высоте", "row": "31", "column": "5"},
        {"coordinate": "G31", "value": f"{not_found}", "row": "31", "column": "7"},
        {"coordinate": "D32", "value": "V", "row": "32", "column": "4"},
        {"coordinate": "E32", "value": "Огневые работы", "row": "32", "column": "5"},
        {"coordinate": "G32", "value": f"{not_found}", "row": "32", "column": "7"},
        {"coordinate": "D33", "value": "□", "row": "33", "column": "4"},
        {"coordinate": "E33", "value": "Оборудование под давлением", "row": "33", "column": "5"},
        {"coordinate": "G33", "value": f"{not_tested}", "row": "33", "column": "7"},
        {"coordinate": "D34", "value": "V", "row": "34", "column": "4"},
        {"coordinate": "E34", "value": "Пожарная безопасность", "row": "34", "column": "5"},
        {"coordinate": "G34", "value": f"{not_found}", "row": "34", "column": "7"},
        {"coordinate": "D35", "value": "V", "row": "35", "column": "4"},
        {"coordinate": "E35", "value": "Первая помощь", "row": "35", "column": "5"},
        {"coordinate": "G35", "value": f"{not_found}", "row": "35", "column": "7"},
        {"coordinate": "D36", "value": "□", "row": "36", "column": "4"},
        {"coordinate": "E36", "value": "Химические, биологические факторы", "row": "36", "column": "5"},
        {"coordinate": "G36", "value": f"{not_tested}", "row": "36", "column": "7"},
        {"coordinate": "D37", "value": "□", "row": "37", "column": "4"},
        {"coordinate": "E37", "value": "Санитарныетребования", "row": "37", "column": "5"},
        {"coordinate": "G37", "value": f"{not_tested}", "row": "37", "column": "7"},
        {"coordinate": "D38", "value": "V", "row": "38", "column": "4"},
        {"coordinate": "E38", "value": "Складирование", "row": "38", "column": "5"},
        {"coordinate": "G38", "value": f"{not_found}", "row": "38", "column": "7"},
        {"coordinate": "D39", "value": "V", "row": "39", "column": "4"},
        {"coordinate": "E39", "value": "Безопасные проходы (лестницы, трапы,мостики)", "row": "39", "column": "5"},
        {"coordinate": "G39", "value": f"{not_found}", "row": "39", "column": "7"},
        {"coordinate": "D40", "value": "V", "row": "40", "column": "4"},
        {"coordinate": "E40", "value": "Отходы", "row": "40", "column": "5"},
        {"coordinate": "G40", "value": f"{not_found}", "row": "40", "column": "7"},
        {"coordinate": "D41", "value": "V", "row": "41", "column": "4"},
        {"coordinate": "E41", "value": "Дежурное освещение, освещенность основных участков работ", "row": "41",
         "column": "5"},
        {"coordinate": "G41", "value": f"{not_found}", "row": "41", "column": "7"},
        {"coordinate": "D42", "value": "V", "row": "42", "column": "4"},
        {"coordinate": "E42", "value": "Другое", "row": "42", "column": "5"},
        {"coordinate": "G42", "value": f"{not_found}", "row": "42", "column": "7"},
        {"coordinate": "C43", "value": "Дополнительная информация", "row": "43", "column": "3"},
        {"coordinate": "C44",
         "value": 'Данное сообщение рассылается Блоком по качеству, охране труда, промышленной безопасности и охране '
                  'окружающей среды АО Мосинжпроект с целью информирования о состоянии площадки, производства и '
                  'документирования строительно-монтажных работ',
         "row": "44", "column": "3"}

    ]

    for val in values:
        try:

            worksheet.cell(row=int(val['row']), column=int(val['column'])).value = str(val['value'])

        except Exception as err:
            logger.error(f"set_values {repr(err)}")
            return None
